### ISSUE TITLE
Esprima Parse Error

### ISSUE THREAD

**Issue by aldendaniels** [spicyj/es3ify#3]
Hello - trying to get started with es3ify. If I can get it to work, this should do exactly what I need. Thank you!

Here's the error I'm getting:
```
/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/jstransform/src/jstransform.js:222
    throw e;
          ^
Error: Parse Error: Line 18: Illegal return statement
    at throwError (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:2159:21)
    at throwErrorTolerant (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:2171:24)
    at parseReturnStatement (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:3873:13)
    at parseStatement (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4115:24)
    at /Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:5832:38
    at parseSourceElement (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4673:24)
    at parseStatementList (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:3274:25)
    at parseBlock (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:3289:17)
    at /Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:5832:38
    at parseStatement (/Users/alden/Source/bidder/ui/node_modules/lib-node/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4088:24)
```

The JS source being parsed is valid (it works without errors in browsers > IE8.

A good starting point would be if es3ify could output error messages that include the file path (and line number if possible) that the parser is choking on.

**Comment by spicyj** [comment]
es3ify doesn't open any files itself – it's up to whatever tool you're using (e.g., browserify) to properly report transform errors. You could *try* adding a console.log of `file` here:

https://github.com/spicyj/es3ify/blob/de5095700270fe8a4d5761c107925b5e50ec8d6a/index.js#L111

Note that `Line 18` is in the error message. Closing as I think this isn't really es3ify's job to fix.

**Comment by aldendaniels** [comment]
@spicyj - I'm aware that browserify transforms are handed vinyl virtual file objects, not real files. I'm suggesting that es3ify should catch errors thrown by esprima and add the file path from the vinyl error message to make debugging easier down the line.

**Comment by spicyj** [comment]
I understand your suggestion. I believe that showing the filename in case of exception should be handled by browserify itself. In some cases you want exceptions to go to your terminal; in others you want the module to be replaced by one that gives an error in your browser when being required. es3ify can't know what's appropriate because it's too low-level.
